fragment TagDetails on Tag {
  id
  slug
  name
  names {
    lang
    value
  }
  valueType
  disciplines
  min
  max
  step
  multiple
  values {
    id
    name
    names {
      lang
      value
    }
  }
  required
  system
}
