fragment TrickSubmissionRow on TrickSubmission {
  id
  kind
  submitter {
    id
    name
    username
  }
  attributionName
  discipline
  lang
  name
  alternativeNames
  description
  status
  upload {
    id
    status
    error
  }
  video {
    videoId
    slowMoStart
  }
  reviewNote
  trick {
    id
    slug
    en: localisation {
      id
      name
    }
  }
  createdAt
}
