query FindUsers ($query: String!) {
  findUsers (query: $query) {
    id
    name
    email
    username
    photo
    grants {
      type
      lang
      rulesId
      verificationLevel
    }
  }
}
