query TrickOptions ($discipline: Discipline) {
  tricks (discipline: $discipline) {
    id
    slug
    en: localisation {
      id
      name
    }
    ttLevels: levels (rulesId: "tricktionary") {
      id
      level
    }
  }
}
