query Tricks ($discipline: Discipline, $searchQuery: String, $filter: TrickFilter, $statusLang: String, $withTranslation: Boolean!) {
  tricks (discipline: $discipline, searchQuery: $searchQuery, filter: $filter) {
    id
    slug
    discipline
    trickType
    en: localisation {
      id
      name
    }
    translation: localisation (lang: $statusLang) @include(if: $withTranslation) {
      id
      name
      description
    }
    levels {
      id
      rulesId
      level
      verificationLevel
    }
    videos {
      host
      type
    }
  }
}
